[package]
name = "lista_pc"
version = "0.1.0"
authors = ["Mateus Vieira Corrêa <mcorrea.comp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
